use std::sync::atomic::Ordering;
use std::sync::Arc;
use std::time::Instant;

use hyper::{Body, Method, Request, Response, StatusCode};

use super::state::HealthState;

/// Maximum allowed request body size (64 KiB).
const MAX_BODY_BYTES: u64 = 64 * 1024;

/// Append standard security headers to a response builder.
fn security_headers(
    builder: hyper::http::response::Builder,
) -> hyper::http::response::Builder {
    builder
        .header("X-Content-Type-Options", "nosniff")
        .header("X-Frame-Options", "DENY")
        .header("Cache-Control", "no-store")
}

/// Route an incoming HTTP request to the appropriate handler.
pub async fn route(req: Request<Body>, state: Arc<HealthState>) -> Response<Body> {
    // Reject oversized request bodies early
    if let Some(len) = content_length(&req) {
        if len > MAX_BODY_BYTES {
            return json_error(StatusCode::PAYLOAD_TOO_LARGE, "Request body too large");
        }
    }

    state
        .metrics
        .http_requests_total
        .fetch_add(1, Ordering::Relaxed);

    match (req.method(), req.uri().path()) {
        (&Method::GET, "/healthz") => handle_health(state, true).await,
        (&Method::GET, "/readyz") => handle_health(state, false).await,
        (&Method::GET, "/metrics") => handle_metrics(state),
        (&Method::POST, "/mock-llm") => handle_mock_llm(state),

        // Known paths, wrong method
        (_, "/healthz" | "/readyz" | "/metrics") => {
            json_error(StatusCode::METHOD_NOT_ALLOWED, "Only GET is allowed")
        }
        (_, "/mock-llm") => {
            json_error(StatusCode::METHOD_NOT_ALLOWED, "Only POST is allowed")
        }

        // Unknown path
        _ => json_error(StatusCode::NOT_FOUND, "Not found"),
    }
}

// ── Handlers ──────────────────────────────────────────────────────────────

async fn handle_health(state: Arc<HealthState>, is_liveness: bool) -> Response<Body> {
    if is_liveness {
        state
            .metrics
            .healthz_requests_total
            .fetch_add(1, Ordering::Relaxed);
    } else {
        state
            .metrics
            .readyz_requests_total
            .fetch_add(1, Ordering::Relaxed);
    }

    let started = Instant::now();
    let report = state.check().await;
    let duration_ms = u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX);

    state
        .metrics
        .health_checks_total
        .fetch_add(1, Ordering::Relaxed);
    state
        .metrics
        .health_check_duration_ms_sum
        .fetch_add(duration_ms, Ordering::Relaxed);
    state
        .metrics
        .health_check_last_duration_ms
        .store(duration_ms, Ordering::Relaxed);

    let is_ok: u64 = u64::from(report.status == "ok");
    state
        .metrics
        .health_check_last_ok
        .store(is_ok, Ordering::Relaxed);
    if is_ok == 0 {
        state
            .metrics
            .health_checks_failed_total
            .fetch_add(1, Ordering::Relaxed);
    }

    let body = serde_json::to_string(&report)
        .unwrap_or_else(|_| r#"{"status":"error"}"#.to_string());
    let status = if report.status == "ok" {
        StatusCode::OK
    } else {
        StatusCode::SERVICE_UNAVAILABLE
    };

    json_response(status, body)
}

fn handle_metrics(state: Arc<HealthState>) -> Response<Body> {
    state
        .metrics
        .metrics_requests_total
        .fetch_add(1, Ordering::Relaxed);

    let body = state.metrics.render_prometheus();

    security_headers(Response::builder())
        .status(StatusCode::OK)
        .header("Content-Type", "text/plain; version=0.0.4; charset=utf-8")
        .body(Body::from(body))
        .unwrap()
}

fn handle_mock_llm(state: Arc<HealthState>) -> Response<Body> {
    if !state.mock_llm_enabled {
        return json_error(StatusCode::NOT_FOUND, "Mock LLM not enabled");
    }

    state
        .metrics
        .mock_llm_requests_total
        .fetch_add(1, Ordering::Relaxed);

    let body = r#"{"content":"[demo] prompt generated by local mock LLM","usage":{"total_tokens":0}}"#;
    json_response(StatusCode::OK, body.to_string())
}

// ── Response helpers ──────────────────────────────────────────────────────

fn json_response(status: StatusCode, body: String) -> Response<Body> {
    security_headers(Response::builder())
        .status(status)
        .header("Content-Type", "application/json")
        .body(Body::from(body))
        .unwrap()
}

fn json_error(status: StatusCode, message: &str) -> Response<Body> {
    let body = serde_json::json!({ "error": message }).to_string();
    json_response(status, body)
}

fn content_length(req: &Request<Body>) -> Option<u64> {
    req.headers()
        .get(hyper::header::CONTENT_LENGTH)?
        .to_str()
        .ok()?
        .parse()
        .ok()
}
